// ==UserScript==
// @name         PoE Cluster Jewel Popup
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Path of Exile trade site cluster jewel description highlighter
// @author       nodeTempest
// @match        https://www.pathofexile.com/trade/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    const data = {
        "prodigious defence": ["+3% Chance to Block Attack Damage", "Blocks Spells", "30% increased Attack Damage while holding a Shield"],
        "advance guard": ["Attack Skills deal 30% increased Damage while holding a Shield", "5% increased Movement Speed while holding a Shield", "Ignore all Movement Penalties from Armour"],
        "gladiatorial combat": ["2% increased Attack Damage per 75 Armour or Evasion Rating on Shield", "+1% to Critical Strike Multiplier per 10 Maximum Energy Shield on Shield"],
        "strike leader": ["+2% Chance to Block Attack Damage", "Attack Skills deal 30% increased Damage while holding a Shield", "+2 to Melee Strike Range while Holding a Shield"],
        "powerful ward": ["20% chance to gain a Power Charge when you Block", "+6% Chance to Block Spell Damage while at Maximum Power Charges"],
        "enduring ward": ["20% chance to gain an Endurance Charge when you Block", "+6% Chance to Block Attack Damage while at Maximum Endurance Charges"],
        "gladiator's fortitude": ["Attack Skills deal 25% increased Damage while holding a Shield", "5% increased maximum Life"],
        "precise retaliation": ["+40% to Critical Strike Multiplier if you have Blocked Recently", "80% increased Critical Strike Chance if you haven’t Blocked Recently"],
        "veteran defender": ["+15 to all Attributes", "60% increased Defences from Equipped Shield", "+15% Elemental Resistances while holding a Shield"],
        "iron breaker": ["Enemies have -10% to Total Physical Damage Reduction against your Hits", "35% increased Physical Damage"],
        "deep cuts": ["15% chance to Impale Enemies on Hit with Attacks", "Impales you inflict last 1 additional Hit"],
        "master the fundamentals": ["35% increased Physical Damage", "35% reduced Elemental Damage", "+10% to all Elemental Resistances"],
        "force multiplier": ["25% increased Physical Damage", "5% chance to deal Double Damage"],
        "furious assault": ["25% increased Physical Damage", "8% increased Attack and Cast Speed"],
        "vicious skewering": ["15% increased Effect of Impales inflicted by Hits that also inflict Bleeding", "10% chance to Impale Enemies on Hit with Attacks", "Attacks have 10% chance to cause Bleeding"],
        "grim oath": ["Gain 10% of Physical Damage as Extra Chaos Damage"],
        "battle-hardened": ["35% increased Physical Damage", "30% increased Evasion Rating and Armour"],
        "replenishing presence": ["Auras from your Skills grant 0.1% of Life Regenerated per second to", "you and Allies", "8% increased effect of Non-Curse Auras from your Skills"],
        "master of command": ["50% reduced Mana Reservation of Banner Skills", "15% increased Effect of Non-Curse Auras from your Skills on Enemies"],
        "first among equals": ["10% increased effect of Non-Curse Auras from your Skills", "Non-Curse Aura Skills have 20% increased Duration"],
        "purposeful harbinger": ["Aura Buffs from Skills have 10% increased Effect on you for each Herald affecting you"],
        "precise commander": ["You and nearby Allies have 50% increased Critical Strike Chance", "You and nearby Allies have +15% to Critical Strike Multiplier"],
        "pure commander": ["Purity of Fire has 30% increased Aura Effect", "Purity of Ice has 30% increased Aura Effect", "Purity of Lightning has 30% increased Aura Effect", "Purity of Elements has 30% increased Aura Effect"],
        "stalwart commander": ["Determination has 30% increased Aura Effect", "Grace has 30% increased Aura Effect", "Discipline has 30% increased Aura Effect"],
        "vengeful commander": ["Anger has 30% increased Aura Effect", "Hatred has 30% increased Aura Effect", "Wrath has 30% increased Aura Effect"],
        "skullbreaker": ["+20% to Critical Strike Multiplier", "8% reduced Enemy Stun Threshold"],
        "pressure points": ["40% increased Critical Strike Chance", "Your Critical Strikes have a 5% chance to deal Double Damage"],
        "overwhelming malice": ["10% chance to gain Unholy Might for 4 seconds on Critical Strike"],
        "magnifier": ["10% increased Area of Effect", "10% increased Area Damage", "+10% to Critical Strike Multiplier"],
        "savage response": ["40% increased Critical Strike Chance", "+50% to Critical Strike Multiplier if you've taken a Savage Hit Recently"],
        "eye of the storm": ["40% increased Critical Strike Chance", "+20% to Damage over Time Multiplier for Ignite from Critical Strikes", "20% increased Effect of Chill you inflict with Critical Strikes", "20% increased Effect of Shock you inflict with Critical Strikes"],
        "basics of pain": ["20% increased Damage", "30% increased Critical Strike Chance"],
        "quick getaway": ["5% increased Attack and Cast Speed", "25% increased Critical Strike Chance", "5% increased Movement Speed if you've dealt a Critical Strike Recently"],
        "assert dominance": ["15% increased Area of Effect if you've Killed Recently", "10% increased Area of Effect if you've Killed at least 5 Enemies Recently", "10% increased Area Damage"],
        "vast power": ["3% increased Area of Effect per Power Charge", "20% increased Area Damage"],
        "powerful assault": ["20% increased Area Damage", "Area Skills have 10% chance to Knock Enemies Back on Hit"],
        "intensity": ["10% increased Area Damage", "Skills supported by Intensify have +1 to maximum Intensity"],
        "titanic swings": ["15% increased Area of Effect while wielding a Two Handed Melee Weapon", "20% increased Area Damage while wielding a Two Handed Melee Weapon"],
        "towering threat": ["10% increased Area of Effect", "5% increased maximum Life", "3% increased Character Size"],
        "ancestral echo": ["20% increased Totem Placement speed", "10% increased Attack and Cast Speed if you've summoned a Totem Recently"],
        "ancestral reach": ["25% increased Totem Damage", "25% increased Totem Placement speed", "25% increased Totem Placement range"],
        "ancestral might": ["20% increased Totem Damage", "30% increased Totem Duration", "30% increased Totem Damage if you haven't Summoned a Totem in the past 2 seconds"],
        "ancestral preservation": ["30% increased Totem Life", "Totems have 10% additional Physical Damage Reduction", "Totems gain + 40% to Chaos Resistance"],
        "snaring spirits": ["30% increased Totem Damage", "Totems Hinder Enemies near them when Summoned, with 25% reduced Movement Speed"],
        "sleepless sentries": ["20% increased Totem Damage", "20% increased Totem Duration", "Attack Skills have +1 to maximum number of Summoned Ballista Totems"],
        "ancestral guidance": ["30% increased Effect of Buffs granted by your Active Ancestor Totems", "Totems' Action Speed cannot be modified to below base value"],
        "ancestral inspiration": ["Gain Arcane Surge when you Summon a Totem", "Spells cast by Totems deal 25% increased Damage"],
        "vital focus": ["Regenerate 1.5% of Life per second while Channelling", "Channelling Skills deal 30% increased Damage"],
        "rapid infusion": ["5% increased Movement Speed while you have Infusion", "50% increased Effect of Infusion"],
        "unwavering focus": ["Channelling Skills deal 25% increased Damage", "15% reduced Mana Cost of Channelling Skills", "40% chance to Avoid being Stunned while Channelling"],
        "enduring focus": ["Channelling Skills deal 25% increased Damage", "25% chance to gain an Endurance Charge each second while Channelling"],
        "precise focus": ["50% increased Critical Strike Chance while Channelling", "+30% to Critical Strike Multiplier if you've been Channelling for at least 1 second"],
        "stoic focus": ["Channelling Skills deal 25% increased Damage", "+4% Chance to Block Attack Damage while Channelling", "+4% Chance to Block Spell Damage while Channelling"],
        "hex breaker": ["Immune to Curses while Channelling", "8% increased Attack and Cast Speed while Channelling"],
        "arcane adept": ["Channelling Skills deal 20% increased Damage", "5% increased Attack and Cast Speed while Channelling", "Gain Arcane Surge after Channelling for 1 second"],
        "distilled perfection": ["25% increased Life Recovery from Flasks", "25% increased Mana Recovery from Flasks", "20% increased Flask Effect Duration"],
        "spiked concoction": ["Non-Unique Flasks applied to you have 10% increased Effect", "5% increased Attack and Cast Speed during any Flask Effect"],
        "fasting": ["20% increased Flask Charges gained", "20% increased Movement Speed while under no Flask Effects"],
        "mender's wellspring": ["25% increased Life Recovery from Flasks", "Life Flasks gain 1 Charge every 3 seconds", "Remove Bleeding when you use a Life Flask"],
        "special reserve": ["Regenerate 2% of Life per second during any Flask Effect", "20% increased Damage during any Flask Effect"],
        "numbing elixir": ["3% additional Physical Damage Reduction during Effect of any Life or Mana Flask", "25% increased Life Recovery from Flasks", "25% increased Mana Recovery from Flasks"],
        "mob mentality": ["20% increased Warcry Cooldown Recovery Speed", "You and nearby Party members gain 5 Rage when you Warcry"],
        "cry wolf": ["30% increased Warcry Duration", "30% increased Warcry Buff Effect", "Warcries count as having 10 additional nearby Enemies"],
        "haunting shout": ["20% increased Warcry Cooldown Recovery Speed", "Enemies Taunted by your Warcries are Unnerved", "Enemies Taunted by your Warcries are Intimidated"],
        "lead by example": ["4% additional Physical Damage Reduction if you've Warcried in the past 8 seconds", "4% chance to deal Double Damage if you've Warcried in the past 8 seconds"],
        "provocateur": ["15% increased Warcry Buff Effect", "40% increased Critical Strike Chance against Taunted Enemies", "+15% to Critical Strike Multiplier against Taunted Enemies"],
        "warning call": ["20% increased Warcry Cooldown Recovery Speed", "50% increased Melee Critical Strike Chance if you've Warcried Recently", "+35% to Melee Critical Strike Multiplier if you've Warcried Recently"],
        "rattling bellow": ["Warcry Skills have 40% increased Area of Effect", "Enemies Taunted by you take 5% increased Damage"],
        "bloodscent": ["Attacks with Axes or Swords grant 1 Rage on Hit, no more than once every second"],
        "run through": ["15% increased Physical Damage with Axes or Swords", "10% chance to Impale Enemies on Hit with Axes or Swords", "10% increased Impale Effect", "Axe or Sword Attacks deal 15% increased Damage with Ailments"],
        "wound aggravation": ["20% increased Physical Damage with Axes or Swords", "Axe or Sword Attacks deal 20% increased Damage with Ailments", "+ 10% to Physical Damage over Time Multiplier while wielding an Axe or Sword"],
        "overlord": ["Gain Fortify for 6 seconds on Melee Hit with a Mace, Sceptre or Staff", "30% increased Damage with Maces, Sceptres or Staves"],
        "expansive might": ["Mace, Sceptre or Staff Attacks deal 20% increased Damage with Hits and Ailments", "While stationary, gain 10% increased Area of Effect every second, up to a maximum of 50%"],
        "weight advantage": ["+20 to Strength", "Mace, Sceptre or Staff Attacks deal 30% increased Damage with Hits and Ailments", "4% chance to deal Double Damage while wielding a Mace, Sceptre or Staff"],
        "wind-up": ["10% chance to gain a Power Charge on Non-Critical Strike with a Claw or Dagger", "+15% to Critical Strike Multiplier with Claws or Daggers"],
        "fan of blades": ["Attack Skills fire an additional Projectile while wielding a Claw or Dagger", "20% increased Projectile Attack Damage with Claws or Daggers"],
        "disease vector": ["+10% to Damage over Time Multiplier for Poison while wielding a Claw or Dagger", "Enemies Poisoned by you cannot Regenerate Life"],
        "arcing shot": ["Arrows gain Damage as they travel farther, dealing up to 50% increased Damage with Hits to targets", "Arrows gain Critical Strike Chance as they travel …her, up to 100% increased Critical Strike Chance"],
        "tempered arrowheads": ["Bow Skills have + 10% to Damage over Time Multiplier", "Bow Skills have 20% increased Skill Effect Duration", "10% increased Duration of Ailments inflicted while wielding a Bow"],
        "broadside": ["Bow Skills have 25% increased Area of Effect"],
        "explosive force": ["Gain 10% of Wand Physical Damage as Extra Chaos Damage", "Enemies Killed with Wand Hits have a 10% chance t…, dealing a quarter of their Life as Chaos Damage"],
        "opportunistic fusilade": ["35% increased Damage with Wands if you've dealt a Critical Strike Recently", "50% increased Critical Strike Chance with Wands"],
        "storm's hand": ["Gain 10% of Wand Physical Damage as Extra Lightning Damage", "25% of Wand Physical Damage converted to Lightning Damage"],
        "battlefield dominator": ["15% increased Area of Effect if you've Stunned an Enemy with a Two Handed Melee Weapon Recently", "Attacks with Two Handed Weapons deal 25% increased Damage with Hits and Ailments", "10% reduced Enemy Stun Threshold"],
        "martial mastery": ["+20 to Strength", "10% increased Attack Speed with Two Handed Melee Weapons", "10% increased Attack Speed if you have at least 600 Strength"],
        "surefooted striker": ["8% chance to deal Double Damage if you've dealt a…al Strike with a Two Handed Melee Weapon Recently", "40% increased Critical Strike Chance with Two Handed Melee Weapons"],
        "graceful execution": ["+15 to Dexterity and Intelligence", "5% increased Attack Speed with Two Handed Melee Weapons", "15% increased Accuracy Rating with Two Handed Melee Weapons", "25% increased Critical Strike Chance with Two Handed Melee Weapons"],
        "brutal infamy": ["Attacks with Two Handed Melee Weapons deal 20% increased Damage with Hits and Ailments", "40% increased Damage with Hits and Ailments against Unique Enemies"],
        "fearsome warrior": ["Attacks with Two Handed Melee Weapons deal 25% increased Damage with Hits and Ailments", "8% increased Area of Effect", "25% chance to Intimidate nearby Enemies for 4 seconds on Melee Kill"],
        "combat rhythm": ["10% increased Attack Speed if you've Hit with your Main Hand Weapon Recently", "10% increased Movement Speed if you've Hit with your Off Hand Weapon Recently"],
        "hit and run": ["Attack Skills deal 20% increased Damage while Dual Wielding", "4% chance to Dodge Attack or Spell Hits if you've Hit an Enemy Recently"],
        "insatiable killer": ["Attack Skills deal 20% increased Damage while Dual Wielding", "5% increased Attack Speed while Dual Wielding", "5% chance to gain a Frenzy Charge on Kill while Dual Wielding"],
        "mage bane": ["Attack Skills deal 20% increased Damage while Dual Wielding", "20% chance to gain a Power Charge when you Block", "+5% Chance to Block Spell Damage while Dual Wielding"],
        "martial momentum": ["8% increased Attack Speed while Dual Wielding", "16% increased Accuracy Rating while Dual Wielding", "32% increased Damage if you've used a Travel Skill Recently"],
        "deadly repartee": ["Attack Skills deal 25% increased Damage while Dual Wielding", "+5% Chance to Block Attack Damage while Dual Wielding", "30% increased Attack Critical Strike Chance while Dual Wielding"],
        "quick and deadly": ["60% increased Main Hand Attack Damage while wielding two different Weapon Types", "30% increased Off Hand Attack Speed while wielding two different Weapon Types"],
        "smite the weak": ["Attacks have 10% chance to Maim on Hit", "40% increased Attack Damage against Maimed Enemies"],
        "heavy hitter": ["30% increased Attack Damage", "30% increased Damage with Ailments from Attack Skills", "10% reduced Enemy Stun Threshold", "20% chance to double Stun Duration"],
        "martial prowess": ["20% increased Attack Damage", "6% increased Attack Speed", "15% increased Global Accuracy Rating", "20% increased Damage with Ailments from Attack Skills"],
        "calamitous": ["30% increased Elemental Damage with Attack Skills", "10% chance to Freeze, Shock and Ignite", "15% increased Effect of Non-Damaging Ailments"],
        "devastator": ["20% increased Attack Damage", "20% increased Damage with Ailments from Attack Skills", "Enemies Killed with Attack Hits have a 15% chance… dealing a tenth of their Life as Physical Damage"],
        "fuel the fight": ["8% increased Attack Speed", "0.4% of Attack Damage Leeched as Mana", "20% increased Damage while Leeching"],
        "drive the destruction": ["0.8% of Attack Damage Leeched as Life", "20% increased Maximum total Recovery per second from Life Leech", "20% increased total Recovery per second from Life Leech"],
        "feed the fury": ["0.4% of Attack Damage Leeched as Life", "30% increased Damage while Leeching", "15% increased Attack Speed while Leeching"],
        "seal mender": ["Skills Supported by Unleash have 30% increased Seal gain frequency"],
        "conjured wall": ["25% increased Spell Damage", "+6% Chance to Block Spell Damage if you've Cast a Spell Recently"],
        "arcane heroism": ["10% chance to gain Arcane Surge when you Hit a Unique enemy", "30% increased Effect of Arcane Surge on you"],
        "practiced caster": ["20% increased Spell Damage", "5% increased Cast Speed", "35% chance to Avoid interruption from Stuns while Casting"],
        "burden projection": ["30% increased Spell Damage", "8% chance to Knock Enemies Back on Hit with Spell Damage"],
        "thaumophage": ["0.6% of Spell Damage Leeched as Energy Shield", "20% increased Maximum total Recovery per second from Energy Shield Leech", "10% chance to Hinder Enemies on Hit with Spells, with 30% reduced Movement Speed"],
        "essence rush": ["0.3% of Spell Damage Leeched as Energy Shield", "5% increased Attack and Cast Speed while Leeching Energy Shield", "40% increased Damage while Leeching Energy Shield"],
        "sap psyche": ["20% increased Spell Damage", "30% increased Mana Regeneration Rate", "Regenerate 1% of Energy Shield per second if you’ve Cursed an Enemy Recently"],
        "sadist": ["15% increased Elemental Damage if you've Chilled an Enemy Recently", "25% increased Elemental Damage if you've Shocked an Enemy Recently", "20% increased Elemental Damage if you've Ignited an Enemy Recently"],
        "corrosive elements": ["Fire Skills have a 25% chance to apply Fire Exposure on Hit", "Cold Skills have a 25% chance to apply Cold Exposure on Hit", "Lightning Skills have a 25% chance to apply Lightning Exposure on Hit", "15% increased Elemental Damage"],
        "doryani's lesson": ["25% increased Elemental Damage", "0.2% of Elemental Damage Leeched as Life"],
        "disorienting display": ["25% increased Elemental Damage", "10% chance to Blind nearby Enemies when you use an Elemental Skill"],
        "prismatic heart": ["30% increased Elemental Damage", "+10% to all Elemental Resistances"],
        "widespread destruction": ["20% increased Elemental Damage", "10% increased Area of Effect"],
        "master of fire": ["Nearby Enemies have Fire Exposure", ""],
        "smoking remains": ["35% increased Fire Damage", "10% chance to create a Smoke Cloud on Kill"],
        "cremator": ["30% increased Fire Damage", "Ignited Enemies you hit are destroyed on Kill"],
        "snowstorm": ["Gain 10% of Lightning Damage as Extra Cold Damage against Chilled Enemies"],
        "storm drinker": ["Damage Penetrates 8% Lightning Resistance", "0.5% of Lightning Damage Leeched as Energy Shield"],
        "paralysis": ["30% increased Lightning Damage", "Lightning Skills have 10% reduced Enemy Stun Threshold", "10% chance to double Stun Duration"],
        "supercharge": ["Lightning Damage with Non-Critical Strikes is Lucky"],
        "blanketed snow": ["Damage Penetrates 10% Cold Resistance against Chilled Enemies"],
        "cold to the core": ["1% increased Cold Damage per 25 Strength", "1% increased Cold Damage per 25 Dexterity", "1% increased Cold Damage per 25 Intelligence"],
        "cold-blooded killer": ["20% increased Cold Damage", "Recover 2% of Life on Kill"],
        "touch of cruelty": ["Chaos Skills have 10% chance to Hinder Enemies on Hit, with 30% reduced Movement Speed", "Enemies Hindered by you take 10% increased Chaos Damage"],
        "unwaveringly evil": ["30% increased Chaos Damage", "Chaos Skills ignore interruption from Stuns"],
        "unspeakable gifts": ["Enemies you Kill have a 10% chance to Explode, de…g a quarter of their maximum Life as Chaos Damage"],
        "dark ideation": ["2% increased Chaos Damage per 100 maximum Mana, up to a maximum of 80%"],
        "unholy grace": ["30% increased Chaos Damage", "10% increased Attack and Cast Speed"],
        "wicked pall": ["35% increased Chaos Damage", "20% increased Skill Effect Duration"],
        "renewal": ["Minions have 10% chance to deal Double Damage while they are on Full Life", "Minions Regenerate 1% of Life per second"],
        "raze and pillage": ["Minions gain 6% of Physical Damage as Extra Fire Damage", "Minions have 20% chance to Ignite", "Minions deal 20% increased Damage against Ignited Enemies"],
        "rotten claws": ["Minions have a 20% chance to Impale on Hit with Attacks"],
        "call to the slaughter": ["Minions deal 15% increased Damage", "Minions created Recently have 30% increased Movement Speed", "Minions created Recently have 10% increased Attack and Cast Speed"],
        "skeletal atrophy": ["Summoned Skeletons have 30% of Physical Damage Converted to Chaos Damage", "Summoned Skeletons have 10% chance to Wither Enemies for 2 seconds on Hit"],
        "hulking corpses": ["20% increased Raised Zombie Size", "Minions have 20% increased maximum Life", "Raised Zombies have 5% chance to Taunt Enemies on Hit"],
        "vicious bite": ["Raised Spectres, Raised Zombies, and Summoned Skeletons have + 50% to Critical Strike Multiplier", "Minions have 50% increased Critical Strike Chance"],
        "primordial bond": ["10% increased Damage per Summoned Golem", "40% increased Effect of Buffs granted by your Golems", "Golems have 25% increased Maximum Life"],
        "blowback": ["Ignites you inflict deal Damage 15% faster"],
        "fan the flames": ["Ignites you inflict spread to other Enemies within a Radius of 15"],
        "cooked alive": ["15% chance to Ignite", "Enemies Ignited by you have -10% to Fire Resistance"],
        "burning bright": ["+8% to Fire Damage over Time Multiplier", "20% increased Fire Damage", "8% increased Area of Effect"],
        "wrapped in flame": ["20% increased Burning Damage", "+15% to Fire Damage over Time Multiplier while Burning", "Regenerate 1.5% of Life per second while Burning"],
        "vivid hues": ["+12% to Damage over Time Multiplier for Bleeding", "2% of Attack Damage Leeched as Life against Bleeding Enemies", "20% increased total Recovery per second from Life Leech"],
        "rend": ["+12% to Damage over Time Multiplier for Bleeding", "30% increased Bleeding Duration"],
        "disorienting wounds": ["25% increased Damage with Bleeding", "25% chance to Blind with Hits against Bleeding Enemies"],
        "compound injury": ["50% increased Damage with Bleeding you inflict on Maimed Enemies"],
        "septic spells": ["20% chance to Poison on Hit with Spell Damage", "Spell Skills have + 10% to Damage over Time Multiplier for Poison", "8% increased Cast Speed"],
        "low tolerance": ["+8% to Damage over Time Multiplier for Poison", "Poisons you inflict on non-Poisoned Enemies deal 300% increased Damage"],
        "steady torment": ["+ 10% to Damage over Time Multiplier for Bleeding you inflict on Poisoned Enemies", "+ 10% to Damage over Time Multiplier for Poison you inflict on Bleeding Enemies", "20% increased Bleeding Duration", "20% increased Poison Duration"],
        "eternal suffering": ["+5% to Chaos Damage over Time Multiplier", "Chaos Skills have 30% increased Skill Effect Duration"],
        "eldritch inspiration": ["+8% to Chaos Damage over Time Multiplier", "16% increased maximum Mana", "20% increased Mana Regeneration Rate"],
        "wasting affliction": ["20% increased Damage with Ailments", "Damaging Ailments deal damage 10% faster"],
        "haemorrhage": ["40% increased Critical Strike Chance", "+18% to Damage over Time Multiplier for Ailments from Critical Strikes"],
        "flow of life": ["24% increased Damage over Time", "4% increased maximum Life", "Regenerate 0.6% of Life per second"],
        "exposure therapy": ["+10% to Damage over Time Multiplier", "+30% Chaos Resistance against Damage Over Time"],
        "brush with death": ["+10% to Damage over Time Multiplier", "Recover 1% of Life on Kill", "Recover 1% of Energy Shield on Kill"],
        "vile reinvigoration": ["24% increased Damage over Time", "6% increased maximum Energy Shield", "Regenerate 2% of Energy Shield per second if you’ve Killed an Enemy Recently"],
        "circling oblivion": ["20% increased Damage over Time", "15% increased Skill Effect Duration", "20% increased Duration of Ailments on Enemies"],
        "brewed for potency": ["24% increased Damage over Time", "20% increased Life and Mana Recovery from Flasks", "10% increased Flask Charges gained"],
        "astonishing affliction": ["20% increased Effect of Non-Damaging Ailments", "20% increased Damage with Hits and Ailments against Enemies affected by Ailments", "20% increased Duration of Elemental Ailments on Enemies"],
        "cold conduction": ["Enemies Chilled by your Hits are Shocked", "Enemies Shocked by your Hits are Chilled"],
        "inspired oppression": ["10% increased Effect of Non-Damaging Ailments", "20% increased Elemental Damage", "30% increased Mana Regeneration Rate if you have Frozen an Enemy Recently", "30% increased Mana Regeneration Rate if you have Shocked an Enemy Recently"],
        "chilling presence": ["Nearby Enemies are Chilled", ""],
        "deep chill": ["+10% to Cold Damage over Time Multiplier", "30% increased Effect of Chill"],
        "blast-freeze": ["20% increased Cold Damage", "Freezes you inflict spread to other Enemies within a Radius of 12"],
        "thunderstruck": ["20% increased Lightning Damage", "30% increased Critical Strike Chance", "Your Critical Strikes Knock Back Shocked Enemies"],
        "stormrider": ["10% chance to gain a Power Charge when you Shock a Chilled Enemy", "25% increased Cold Damage with Hits against Shocked Enemies", "25% increased Lightning Damage with Hits against Chilled Enemies"],
        "overshock": ["30% increased Lightning Damage", "30% increased Effect of Shock", "Your Shocks can increase Damage taken by up to a maximum of 60%"],
        "evil eye": ["Enemies you Curse take 5% increased Damage", "5% chance to Dodge Attack Hits from Cursed Enemies"],
        "whispers of death": ["5% increased Effect of your Curses", "20% increased Damage if you've Killed a Cursed Enemy Recently"],
        "forbidden words": ["25% increased Area of Effect of Curse Skills", "Curse Skills have 5% reduced Mana Reservation", "5% increased Effect of your Curses"],
        "dark discourse": ["10% increased Effect of your Curses", "Enemies you Curse are Hindered, with 15% reduced Movement Speed", "Regenerate 1% of Energy Shield per second if you’ve Killed an Enemy Recently"],
        "victim maker": ["25% increased Damage with Hits and Ailments against Cursed Enemies", "Curse Skills have 50% increased Skill Effect Duration"],
        "master of fear": ["Enemies you Curse are Intimidated", "Enemies you Curse are Unnerved"],
        "wish for death": ["Curse Skills have 20% increased Skill Effect Duration", "You have Culling Strike against Cursed Enemies"],
        "heraldry": ["20% increased Effect of Herald Buffs on you", "10% reduced Mana Reservation of Herald Skills"],
        "endbringer": ["25% increased Damage for each Herald affecting you"],
        "cult-leader": ["Minions deal 35% increased Damage while you are affected by a Herald"],
        "empowered envoy": ["Herald Skills deal 40% increased Damage", "20% increased Effect of Herald Buffs on you"],
        "dark messenger": ["Herald Skills deal 20% increased Damage", "Herald Skills have 25% increased Area of Effect"],
        "agent of destruction": ["25% increased Elemental Damage while affected by a Herald", "10% chance to Freeze, Shock and Ignite while affected by a Herald"],
        "lasting impression": ["Herald Skills deal 50% increased Damage over Time", "30% increased Damage over Time while affected by a Herald"],
        "self-fulfilling prophecy": ["+25% to Critical Strike Multiplier if you dealt a Critical Strike with a Herald Skill Recently", "+1% to Critical Strike Chance of Herald Skills"],
        "invigorating portents": ["Minions deal 20% increased Damage while you are affected by a Herald", "Minions have 10% increased Movement Speed for each Herald affecting you"],
        "pure agony": ["Minions deal 20% increased Damage while you are affected by a Herald", "+1 to maximum number of Sentinels of Purity", "+5 to Maximum Virulence"],
        "disciples": ["Minions deal 20% increased Damage while you are affected by a Herald", "1% additional Physical Damage Reduction per Summoned Sentinel of Purity", "You lose Virulence 30% slower"],
        "dread march": ["Minions have 10% increased maximum Life", "Minions have 10% additional Physical Damage Reduction", "Minions have +10% to Chaos Resistance", "Minions have 10% increased Movement Speed"],
        "blessed rebirth": ["Minions have 20% increased maximum Life", "Minions created Recently cannot be Damaged"],
        "life from death": ["Minions have 15% increased maximum Life", "Regenerate 2% of Life per second if a Minion has Died Recently", "Minions Recover 4% of Life on Minion Death"],
        "feasting fiends": ["Minions have 10% increased maximum Life", "Minions deal 10% increased Damage", "Minions Leech 0.4% of Damage as Life"],
        "bodyguards": ["Minions have 10% increased maximum Life", "Minions have 10% chance to Knock Enemies Back on Hit with Attacks"],
        "follow-through": ["Projectiles deal 15% increased Damage for each remaining Chain"],
        "streamlined": ["20% increased Projectile Damage", "30% increased Projectile Speed"],
        "shrieking bolts": ["35% increased Projectile Damage", "10% chance to Taunt Enemies on Projectile Hit"],
        "eye to eye": ["25% increased Projectile Damage", "35% increased Projectile Damage with Hits against Nearby Enemies"],
        "repeater": ["30% increased Projectile Damage", "8% increased Attack and Cast Speed"],
        "aerodynamics": ["10% increased Projectile Damage", "20% increased Projectile Speed", "Projectiles Pierce an additional Target"],
        "chip away": ["25% increased Brand Activation Frequency if you haven't used a Brand Skill Recently", "20% increased Brand Attachment range"],
        "seeker runes": ["25% increased Damage with Brand Skills", "Unattached Brands gain 20% increased Brand Attachment Range per second"],
        "remarkable": ["12% increased Cast Speed with Brand Skills", "You can Cast an additional Brand"],
        "brand loyalty": ["20% increased Brand Attachment range", "Enemies take 5% increased Damage for each of your Brands Attached to them"],
        "holy conquest": ["20% increased Damage with Brand Skills", "10% increased Brand Activation frequency", "5% increased Movement Speed"],
        "grand design": ["Brand Skills have 20% increased Duration", "10% increased Brand Activation frequency", "20% increased Brand Attachment range", "You can Cast an additional Brand"],
        "set and forget": ["25% increased Trap Damage", "40% increased Trap Trigger Area of Effect", "12% increased Area of Effect", "25% reduced Trap Duration"],
        "expert sabotage": ["30% increased Mine Damage", "Can have up to 2 additional Remote Mines placed at a time", "Mines have 20% increased Detonation Speed"],
        "guerilla tactics": ["20% increased Trap Damage", "20% increased Mine Damage", "10% increased Trap Throwing Speed", "10% increased Mine Throwing Speed", "5% increased Movement Speed if you've thrown a Trap or Mine Recently"],
        "expendability": ["10% chance to throw up to 1 additional Trap or Mine"],
        "arcane pyrotechnics": ["20% increased Trap Damage", "20% increased Mine Damage", "Gain Arcane Surge when your Trap is Triggered by an Enemy", "Gain Arcane Surge when your Mine is Detonated targeting an Enemy"],
        "surprise sabotage": ["+15% to Critical Strike Multiplier with Traps", "+15% to Critical Strike Multiplier with Mines", "Trap Damage Penetrates 5% Elemental Resistances", "Mine Damage Penetrates 5% Elemental Resistances"],
        "careful handling": ["15% increased Trap Damage", "15% increased Mine Damage", "4% increased maximum Life", "6% increased maximum Mana"],
        "peak vigour": ["8% increased maximum Life", "30% increased Life Recovery from Flasks"],
        "fettle": ["10% increased maximum Life", "+20 to maximum Life"],
        "feast of flesh": ["8% increased maximum Life", "0.4% of Attack Damage Leeched as Life", "+10 Life gained for each Enemy hit by your Attacks"],
        "sublime sensation": ["8% increased maximum Life", "10% increased maximum Energy Shield"],
        "surging vitality": ["8% increased maximum Life", "Every 5 seconds, Regenerate 10% of Life over one second", "Regenerate 0.5% of Life per second"],
        "peace amidst chaos": ["8% increased maximum Life", "Regenerate 2% of Life per second while stationary", "2% additional Physical Damage Reduction while stationary"],
        "adrenaline": ["6% increased maximum Life", "15% increased Maximum total Recovery per second from Life Leech", "6% increased Attack Speed while Leeching"],
        "wall of muscle": ["6% increased maximum Life", "5% increased Strength"],
        "mindfulness": ["15% increased maximum Mana", "80% increased Mana Regeneration Rate while stationary"],
        "liquid inspiration": ["15% increased maximum Mana", "30% increased Mana Recovery from Flasks", "5% increased Mana Recovery Rate during Effect of any Mana Flask"],
        "openness": ["+30 to maximum Mana", "20% increased maximum Mana"],
        "daring ideas": ["18% increased maximum Mana", "0.4% of Attack Damage Leeched as Mana"],
        "clarity of purpose": ["15% increased maximum Mana", "30% increased Mana Regeneration Rate"],
        "scintillating idea": ["20% increased maximum Mana", "Damage Penetrates 5% Lightning Resistance"],
        "holistic health": ["8% increased maximum Life", "10% increased maximum Mana"],
        "genius": ["8% increased maximum Mana", "5% increased Intelligence"],
        "improvisor": ["6% increased Attack Speed", "10% increased maximum Mana", "+3 Mana gained for each Enemy hit by your Attacks"],
        "stubborn student": ["4% additional Physical Damage Reduction", "15% increased maximum Mana", "20% increased Armour"],
        "savour the moment": ["10% increased maximum Energy Shield", "Regenerate 3% of Energy Shield per second while stationary"],
        "energy from naught": ["+100 to maximum Energy Shield"],
        "will shaper": ["Gain 5% of Maximum Mana as Extra Maximum Energy Shield"],
        "spring back": ["6% increased maximum Energy Shield", "10% faster start of Energy Shield Recharge", "15% increased Energy Shield Recharge Rate"],
        "conservation of energy": ["8% increased maximum Energy Shield", "0.3% of Spell Damage Leeched as Energy Shield", "20% increased Maximum total Recovery per second from Energy Shield Leech"],
        "heart of iron": ["Gain 10% of Maximum Life as Extra Armour"],
        "prismatic carapace": ["+1% to all maximum Elemental Resistances", "30% increased Armour"],
        "militarism": ["8% increased maximum Life", "30% increased Armour"],
        "second skin": ["+3% Chance to Block Attack Damage", "Blocks Spells", "30% increased Armour"],
        "dragon hunter": ["+20% to Fire Resistance", "5% additional Physical Damage Reduction", "30% increased Armour"],
        "enduring composure": ["30% increased Armour", "Gain 1 Endurance Charge every second if you've been Hit Recently"],
        "prismatic dance": ["+1% to all maximum Elemental Resistances", "30% increased Evasion Rating"],
        "natural vigour": ["8% increased maximum Life", "30% increased Evasion Rating"],
        "untouchable": ["3% chance to Dodge Attack Hits", "3% chance to Dodge Spell Hits", "30% increased Evasion Rating"],
        "shifting shadow": ["+20 to Dexterity", "10% chance to Blind Enemies on Hit", "20% increased Evasion Rating"],
        "readiness": ["+4% chance to Evade Attack Hits if you haven't been Hit Recently"],
        "confident combatant": ["1% increased Damage per 1% Chance to Block Attack Damage"],
        "flexible sentry": ["+3% Chance to Block Attack Damage", "Blocks Spells", "25% chance to Avoid Elemental Ailments"],
        "vicious guard": ["+4% Chance to Block Attack Damage", "Regenerate 1.5% of Life per second", "0.4% of Attack Damage Leeched as Life"],
        "mystical ward": ["Blocks Spells", "Regenerate 1.5% of Energy Shield per second", "0.3% of Spell Damage Leeched as Energy Shield"],
        "rote reinforcement": ["+20 to maximum Life", "+4% Chance to Block Attack Damage", "20% chance to gain an Endurance Charge when you Block"],
        "mage hunter": ["20% increased Spell Damage", "Blocks Spells", "20% chance to gain a Power Charge when you Block"],
        "riot queller": ["+4% Chance to Block Attack Damage", "Enemies Taunted by you take 6% increased Damage"],
        "one with the shield": ["Recover 50 Life when you Block", "50% increased Defences from Equipped Shield", "+5% Chance to Block Attack Damage while holding a Shield"],
        "aerialist": ["3% chance to Dodge Attack Hits", "3% chance to Dodge Spell Hits", "5% increased Dexterity"],
        "elegant form": ["3% chance to Dodge Attack Hits", "3% chance to Dodge Spell Hits", "30% chance to Avoid Elemental Ailments"],
        "darting movements": ["5% chance to Dodge Attack and Spell Hits while moving", "5% increased Movement Speed"],
        "no witnesses": ["10% chance to gain Elusive on Kill", "25% increased Elusive Effect"],
        "molten one's mark": ["+2% to maximum Fire Resistance", "Regenerate 1% of Life per second"],
        "fire attunement": ["40% reduced Ignite Duration on you", "50% reduced Extra Damage taken from Critical Strikes while Ignited"],
        "pure might": ["+20 to Strength", "Purity of Fire has 30% reduced Mana Reservation", "40% increased Stun and Block Recovery"],
        "blacksmith": ["+20% to Fire Resistance", "25% increased Armour", "0.4% of Fire Damage Leeched as Life"],
        "non-flammable": ["+20% to Fire Resistance", "40% chance to Avoid being Ignited", "6% chance to Avoid Fire Damage from Hits"],
        "winter prowler": ["+2% to maximum Cold Resistance", "6% increased Movement Speed"],
        "hibernator": ["40% reduced Freeze Duration on you", "15% additional Physical Damage Reduction while Frozen"],
        "pure guile": ["+20 to Dexterity", "Purity of Ice has 30% reduced Mana Reservation", "5% chance to Blind Enemies on Hit"],
        "alchemist": ["+20% to Cold Resistance", "8% increased Attack and Cast Speed", "20% increased Life Recovery from Flasks"],
        "antifreeze": ["+20% to Cold Resistance", "40% chance to Avoid being Frozen", "6% chance to Avoid Cold Damage from Hits"],
        "wizardry": ["+2% to maximum Lightning Resistance", "8% increased maximum Mana"],
        "capacitor": ["40% reduced Effect of Shock on you", "12% increased Movement Speed while Shocked"],
        "pure aptitude": ["+20 to Intelligence", "Purity of Lightning has 30% reduced Mana Reservation", "Regenerate 1% of Energy Shield per second"],
        "sage": ["+20% to Lightning Resistance", "20% increased Mana Regeneration Rate", "Regenerate 1.5% of Life per second"],
        "insulated": ["+20% to Lightning Resistance", "40% chance to Avoid being Shocked", "6% chance to Avoid Lightning Damage from Hits"],
        "born of chaos": ["+3% to maximum Chaos Resistance"],
        "antivenom": ["+17% to Chaos Resistance", "Unaffected by Poison"],
        "rot-resistant": ["+13% to Chaos Resistance", "Regenerate 1.2% of Life per second", "Regenerate 0.6% of Energy Shield per second", "Regenerate 0.3% of Mana per second"],
        "blessed": ["+13% to Chaos Resistance", "6% increased maximum Life", "10% increased maximum Mana"],
        "student of decay": ["+13% to Chaos Resistance", "25% increased Damage over Time"]
    }

    document.addEventListener("mouseover", e => {
        const elem = e.target.closest(".explicitMod .lc.s");
        if (!elem) {
            return;
        }

        const elemText = elem.textContent.toLowerCase();
        const notable = Object.keys(data).find(notable => elemText.includes(notable));

        if (!notable) {
            return;
        }

        const popup = document.createElement("div");

        popup.style.backgroundColor = "black";
        popup.style.color = "white";
        popup.style.position = "fixed";
        popup.style.top = elem.getBoundingClientRect().top + "px";
        popup.style.left = elem.getBoundingClientRect().right + "px";
        popup.style.padding = "8px 8px 0";
        popup.style.zIndex = "999";
        popup.style.width = "fit-content";

        popup.append(
            ...data[notable].map(descriptionText => {
                const p = document.createElement("p");
                p.textContent = descriptionText;
                return p;
            })
        );

        document.body.append(popup);

        const removePopup = () => {
            popup.remove();
            elem.removeEventListener("mouseout", removePopup);
        };

        elem.addEventListener("mouseout", removePopup);
    });
})();
